# Users

## Create user
POST http://localhost:4000/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "firstName": "Jack",
  "password": "shining"
}
###

## Login
POST http://localhost:4000/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}
###

## Upload image
POST http://localhost:4000/user/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png
###

## Check user token
GET http://localhost:4000/v1/user/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdE5hbWUiOiJKYWNrIiwiaWQiOiI2NmFlZjQxOWE1ZjE2NzFlOTI1NjNjZmEiLCJpYXQiOjE3MzIwNzQ4NjMsImV4cCI6MTczMjI0NzY2M30.fmGqTyeblciMBZLXpd62p-ZTHiPATzunM4JCXJ1GiA8
###
